name: Push

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  go-version: 1.22

jobs:
  deploy:
    name: Push the latest image
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - run: docker build -t ghcr.io/jacekzubielik/todo:latest ./todo
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: docker push ghcr.io/jacekzubielik/todo:latest
